title: Australian BioCommons Collections
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

gtag: G-T8GWK081T9
# Adds BioCommons technical documentation analytics tag

topnav_title: Collections
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: ""
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@4.1.0

theme_variables:
  # biocommons blue
  theme_color: 205a86
  topnav:
    brand_logo: assets/img/Australian-Biocommons-Logo-Tagline-Community-RGB.png

exclude:
  - README.md
  - vendor

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - webrick
